name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    
  linux_build_6_4_2:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    - uses: jurplel/install-qt-action@v3
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version: '6.4.2'
        # Host platform
        host: # optional
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: # optional
        # Whether or not to install Qt dependencies on Linux
        install-deps: 'true'
        # Additional Qt modules to install
        modules: 'qt5compat' #'qtscript' # qtcharts, qtdatavis3d, qtpurchasing, qtvirtualkeyboard, qtwebengine, qtnetworkauth, qtwebglplugin, qtscript, debug_info, qtscripttools
        # Force a Qt mirror in case the default is not working
        #mirror: # optional
        # Whether or not to actually download Qt
        #cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.8
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.6
        # Any extra arguments to append to the back
        extra: # optional
    - name: Install Qt and compile
      run: |
        #sudo apt-get install libgtk-3-dev
        pwd 
        ls -lrt
        ls -lrt ..
        ls -lrt ../Qt
        #python3 -m aqt tool -O ../Qt linux tools_ifw 3.2.2 linux-x64
        #ls -lrt ../Qt/Tools
        qmake -r sciteqt.pro
        ls -lrt
        make
        ls -lrt
        ls -lrt scite/qt

