name: MacOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
            
  macos_6_4_2_build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: jurplel/install-qt-action@v3
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version: '6.4.2'
        # Host platform
        host: 'mac'
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: # optional
        # Whether or not to install Qt dependencies on Linux
        install-deps: 'true'
        # Additional Qt modules to install
        modules: 'qt5compat' #'qtscript'
        # Force a Qt mirror in case the default is not working
        #mirror: # optional
        # Whether or not to actually download Qt
        #cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.8
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.6
        # Any extra arguments to append to the back
        extra: # optional
    - name: Install Qt and compile
      run: |
        pwd 
        ls -lrt
        ls -lrt ..
        ls -lrt ../Qt
        #ls -lrt ../Qt/Tools
        #python3 -m aqt tool -O ../Qt mac tools_ifw 3.2.2 mac-x64
        #ls -lrt ../Qt/Tools
        clang++ --version
        sw_vers
        which qmake
        qmake -r sciteqt.pro
        ls -lrt
        make
        ls -lrt
        ls -lrt scite/qt

        #make -j 4
        ls -lrt
        ls -lrt scite
        ls -lrt scite/qt
        cd scite/qt
        which macdeployqt
        macdeployqt sciteqt.app -dmg -qmldir=qml -verbose=2
        ls -lrt        
