name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    
  windows_gcc_build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: jurplel/install-qt-action@v2
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version: '5.14.2'
        # Host platform
        host: # optional
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: 'win64_mingw73'
        # Whether or not to install Qt dependencies on Linux
        install-deps: 'true'
        # Additional Qt modules to install
        modules: 'qtscript qtscripttools'
        # Force a Qt mirror in case the default is not working
        mirror: # optional
        # Whether or not to actually download Qt
        cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.8
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.6
        # Any extra arguments to append to the back
        extra: # optional
    - name: Install Qt and compile
      run: |
        d:
        dir 
        python -m aqt tool -O d:\a\SciTEQt/Qt windows tools_ifw 3.2.2 win-x86
        gcc -v
        qmake -r sciteqt.pro
        dir
        mingw32-make
        dir
        dir scite\bin
        dir scite\qt
        dir scintilla\bin
        #
        #cd scintilla        
        #cd qt
        #cd ScintillaEditBase
        #mingw32-make
        #cd ..
        #cd ..
        #cd ..
        #cd scite
        #cd qt
        #mingw32-make
        #dir
        #cd ..
        #cd ..
        #dir scite 
        #dir scite\qt
        
  windows_msc_build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ilammy/msvc-dev-cmd@v1.0.0
    - uses: jurplel/install-qt-action@v2
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version: '5.14.2'
        # Host platform
        host: # optional
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: 'win64_msvc2017_64'
        # Whether or not to install Qt dependencies on Linux
        install-deps: 'true'
        # Additional Qt modules to install
        modules: 'qtscript qtscripttools'
        # Force a Qt mirror in case the default is not working
        mirror: # optional
        # Whether or not to actually download Qt
        cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.8
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.6
        # Any extra arguments to append to the back
        extra: # optional
    - name: Install Qt and compile
      run: |
        cd 
        dir
        d:
        dir 
        python -m aqt tool -O d:\a\SciteQt/Qt windows tools_ifw 3.2.2 win-x86
        dir d:\a\SciteQt\Qt\Tools
        cl
        where qmake
        qmake -r sciteqt.pro
        dir
        nmake
        dir
        dir scite
        dir scite\qt
        dir scite\qt\release
        dir scite\bin
        dir scintilla\bin
        #dir src\dist\packages\org.scintilla.sciteqt\data
        #cd src\dist\packages\org.scintilla.sciteqt\data
        #windeployqt --release --no-system-d3d-compiler sciteqt.exe
        #dir
        #cd ..\..\..
        #dir
        #d:\a\SciteQt\Qt\Tools\QtInstallerFramework\3.2\bin\binarycreator --offline-only -c config\config.xml -p packages SciteQtInstaller.exe
        #dir 
        #echo %path%
        #where binarycreator
        #binarycreator
        